// LandOS — the operator display location for a canonical property.
//
// LandOS distinguishes five location concepts that one "address" string used
// to conflate:
//
//   1. source / input description — what the seller, operator or feed supplied
//      ("Map 042 Parcel 123"); retained forever as provenance, never rewritten.
//   2. canonical parcel identity — the APN ("042-123.00-000"); display changes
//      never touch it.
//   3. official numbered situs — a genuine numbered address established by an
//      appropriate record ("123 Kingwood Blvd").
//   4. road / frontage location — the recognized road the parcel actually
//      fronts or is served by, established by evidence ("Kingwood Blvd").
//   5. operator display location — the best human-readable location shown
//      prominently to the operator. THIS module derives only concept 5.
//
// Display hierarchy (system-wide, no per-property logic):
//   Tier 1 — a credible real numbered situs displays as-is.
//   Tier 2 — road established but no numbered situs: "0 <Road>, City, ST ZIP".
//            The leading 0 is a LANDOS DISPLAY CONVENTION meaning "road
//            established; no numerical situs address established". It is never
//            an official street number, never attributed to the assessor, and
//            never evidence of anything.
//   Tier 3 — neither: the parcel/map/legal description remains the display.
//
// The ONLY synthetic street number this module may produce is that leading 0.
// A real-looking number is never invented, and an uncertain road is never
// promoted — Tier 2 requires road evidence tied to the subject parcel.

export type OperatorDisplayLocationType =
  | 'numbered_situs'
  | 'landos_road_only'
  | 'parcel_description';

export interface OperatorDisplayLocation {
  /** The full operator-facing location line, locality included when known. */
  displayAddress: string;
  displayType: OperatorDisplayLocationType;
  /** The established frontage/serving road, when concept 4 is established. */
  roadName: string | null;
  /** The genuine official situs street number; null under the 0 convention. */
  officialSitusNumber: string | null;
  /** True when the leading 0 was generated by LandOS. It carries no
   *  evidentiary value and must never be persisted as an official number. */
  landosGeneratedZero: boolean;
}

/** Map/parcel/legal-style descriptions are parcel identity notation, never a
 *  street line: they can never be read as a road or a numbered situs. */
export function isParcelDescription(value: string | null | undefined): boolean {
  const text = String(value ?? '').trim();
  if (!text) return false;
  return /\b(?:map|parcel|apn|pin|lot|block|tract|grp|group|ctrl)\b[\s.:#-]*[0-9]/i.test(text)
    || /^\d{2,4}[-\s]\d{1,3}(?:\.\d{2})?[-\s]\d{3}$/.test(text);
}

/** A street line "123 Kingwood Blvd" split into its number and road. A line
 *  with no leading number is a road-only line. Parcel notation is neither. */
export function parseStreetLine(value: string | null | undefined): {
  number: string | null;
  road: string | null;
} {
  const line = String(value ?? '').split(',')[0]?.trim() ?? '';
  if (!line || isParcelDescription(line)) return { number: null, road: null };
  const match = /^(\d+[A-Za-z]?)\s+(.+)$/.exec(line);
  if (match) return { number: match[1], road: match[2].trim() };
  // No leading number: the line is a road only when it looks like one.
  return /^[A-Za-z][A-Za-z0-9 .'-]*$/.test(line) ? { number: null, road: line } : { number: null, road: null };
}

const ROAD_SUFFIX_ABBREVIATIONS: Record<string, string> = {
  BOULEVARD: 'Blvd', ROAD: 'Rd', STREET: 'St', AVENUE: 'Ave', DRIVE: 'Dr',
  LANE: 'Ln', COURT: 'Ct', CIRCLE: 'Cir', HIGHWAY: 'Hwy', PARKWAY: 'Pkwy',
  PLACE: 'Pl', TRAIL: 'Trl', TERRACE: 'Ter', PIKE: 'Pike', WAY: 'Way',
  BLVD: 'Blvd', RD: 'Rd', ST: 'St', AVE: 'Ave', DR: 'Dr', LN: 'Ln', CT: 'Ct',
  CIR: 'Cir', HWY: 'Hwy', PKWY: 'Pkwy', PL: 'Pl', TRL: 'Trl', TER: 'Ter',
};

/** "KINGWOOD BLVD" → "Kingwood Blvd" (LandOS-standard display formatting). */
export function formatRoadName(road: string): string {
  return road.trim().split(/\s+/).map((token) => {
    const upper = token.toUpperCase();
    if (ROAD_SUFFIX_ABBREVIATIONS[upper]) return ROAD_SUFFIX_ABBREVIATIONS[upper];
    if (/^(?:N|S|E|W|NE|NW|SE|SW|US|SR|TN)$/.test(upper)) return upper;
    return token.charAt(0).toUpperCase() + token.slice(1).toLowerCase();
  }).join(' ');
}

/** PURE: same road, tolerant of case, suffix abbreviation and punctuation. */
export function roadNamesEquivalent(a: string, b: string): boolean {
  const core = (value: string): string => value.toUpperCase().replace(/[^A-Z0-9 ]/g, ' ').trim().split(/\s+/)
    .map((token) => ROAD_SUFFIX_ABBREVIATIONS[token]?.toUpperCase() ?? token)
    .join(' ');
  return !!core(a) && core(a) === core(b);
}

export interface OperatorDisplayLocationInput {
  /** The retained source/input description (concept 1). Always the fallback. */
  sourceDescription: string | null;
  /** The official situs line as the record prints it — may carry a real
   *  number ("123 Kingwood Blvd") or be road-only ("KINGWOOD BLVD"). */
  officialSitus: string | null;
  /** Independently established frontage/serving road evidence (concept 4),
   *  when a lane other than the situs established it. Must belong to the
   *  SUBJECT parcel — a nearby or guessed road never qualifies. */
  establishedRoad?: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
}

function locality(input: Pick<OperatorDisplayLocationInput, 'city' | 'state' | 'zip'>): string {
  return [input.city, [input.state, input.zip].filter(Boolean).join(' ')]
    .filter((part) => part && String(part).trim())
    .join(', ');
}

/**
 * Derive the operator display location for one subject from ITS OWN retained
 * evidence. Deterministic and side-effect free: the same persisted inputs
 * always reconstruct the same display, so a page refresh can never change it.
 */
export function deriveOperatorDisplayLocation(input: OperatorDisplayLocationInput): OperatorDisplayLocation {
  const where = locality(input);
  const withLocality = (line: string): string => (where ? `${line}, ${where}` : line);

  // Tier 1 — a credible real numbered situs wins outright.
  const situs = parseStreetLine(input.officialSitus);
  if (situs.number && situs.road) {
    return {
      displayAddress: withLocality(`${situs.number} ${formatRoadName(situs.road)}`),
      displayType: 'numbered_situs',
      roadName: formatRoadName(situs.road),
      officialSitusNumber: situs.number,
      landosGeneratedZero: false,
    };
  }
  // A numbered SOURCE street address (a genuine lead address, not parcel
  // notation) is likewise a credible numbered situs for display purposes.
  const source = parseStreetLine(input.sourceDescription);
  if (source.number && source.road) {
    return {
      displayAddress: withLocality(`${source.number} ${formatRoadName(source.road)}`),
      displayType: 'numbered_situs',
      roadName: formatRoadName(source.road),
      officialSitusNumber: source.number,
      landosGeneratedZero: false,
    };
  }

  // Tier 2 — road established with no numbered situs: the LandOS 0 convention.
  const road = situs.road ?? (input.establishedRoad ? parseStreetLine(input.establishedRoad).road : null);
  if (road) {
    return {
      displayAddress: withLocality(`0 ${formatRoadName(road)}`),
      displayType: 'landos_road_only',
      roadName: formatRoadName(road),
      officialSitusNumber: null,
      landosGeneratedZero: true,
    };
  }

  // Tier 3 — the parcel/map/source description remains the honest display.
  const fallback = String(input.sourceDescription ?? '').trim() || 'Unlocated parcel';
  return {
    displayAddress: withLocality(fallback),
    displayType: 'parcel_description',
    roadName: null,
    officialSitusNumber: null,
    landosGeneratedZero: false,
  };
}
