// Forge Codex review packet generator — pure Forge Core.
//
// Deterministic, dependency-free, host-neutral. Produces a copy-ready Codex
// review PROMPT (plain text) for a Forge engagement. It generates text only:
// it never runs Codex, never executes anything, makes no network calls, reads
// no env, and touches no secrets. The host layer supplies runtime facts
// (repo path, commit hashes, changed files); anything missing renders as an
// explicit placeholder so the operator can fill it in.

export interface ReviewPacketInput {
  title?: string;
  repoPath?: string;
  currentCommit?: string;
  previousPushedCommit?: string;
  expectedChangedFiles?: string[];
  verdict?: 'SAFE' | 'STOP';
  rawRequest?: string;
  /** Commands the reviewer should run. Defaults to the Forge-standard set. */
  testsToRun?: string[];
}

const PLACEHOLDER = '<fill in>';

const DEFAULT_TESTS = [
  'npx vitest run src/forge/engagement.test.ts',
  'npx vitest run src/dashboard.contract.test.ts -t "forge"',
  'npm run typecheck',
  'npm run build:web',
];

const ARCHITECTURE_RULES = [
  'Forge Core (src/forge/engagement.ts, review-packet.ts, command-planner.ts) must stay pure: deterministic, dependency-free, host-neutral, no network, no env, no secrets.',
  'Persistence, dashboard UI, and host routing belong in the host adapter layer (host-store.ts, dashboard.ts, web/), never in Forge Core.',
  'Forge Core stays universal and industry-neutral: no business- or domain-specific concepts belong in it.',
  'No new dependencies without explicit approval.',
];

const SECURITY_RULES = [
  'No command execution from generated artifacts or review packets.',
  'No git push, deploy, install, or destructive actions performed by Forge.',
  'No .env reads or secret prints. Markdown rendering stays sanitized.',
  'No paid APIs, no external network calls.',
];

function mdList(items: string[]): string {
  return items.length ? items.map((i) => `- ${i}`).join('\n') : `- ${PLACEHOLDER}`;
}

/**
 * Build a copy-ready Codex review packet for an engagement. Pure: same input
 * always yields the same text.
 */
export function generateReviewPacket(input: ReviewPacketInput): string {
  const title = input.title?.trim() || 'Forge engagement';
  const repoPath = input.repoPath?.trim() || PLACEHOLDER;
  const currentCommit = input.currentCommit?.trim() || PLACEHOLDER;
  const previousPushedCommit = input.previousPushedCommit?.trim() || PLACEHOLDER;
  const verdict = input.verdict ?? 'SAFE';
  const tests = input.testsToRun && input.testsToRun.length ? input.testsToRun : DEFAULT_TESTS;
  const changed = input.expectedChangedFiles ?? [];
  const rawRequest = input.rawRequest?.trim() || PLACEHOLDER;

  return `# Codex Review Packet — ${title}

Repo:
${repoPath}

Current commit:
${currentCommit}

Previous pushed commit:
${previousPushedCommit}

Lane verdict at generation time: ${verdict}

Original request:
${rawRequest}

Expected changed files:
${mdList(changed)}

Architecture rules to verify:
${mdList(ARCHITECTURE_RULES)}

Security rules to verify:
${mdList(SECURITY_RULES)}

Tests to run:
${mdList(tests)}

Reviewer instructions:
- Review only. Do NOT modify, stage, commit, or push anything.
- Do NOT execute anything generated by Forge artifacts or this packet.
- Do NOT read or print .env or any secret.
- Confirm Forge Core stayed pure, or that any change to it was a justified small bug fix.

Final format required from the reviewer:
- Verdict: PASS or FAIL
- Findings: numbered list (empty if none)
- Safe to push: Yes or No
- Recommended next step: one line
`;
}
